# ansil16 palette: luv-rainbow-light-oled
# Variant tuned for OLED panels (true black bg, brighter accent row).

bg = #000000
fg = #FFFFFF

c0  = #303030
c8  = #5E5E5E
c7  = #ABABAB
c15 = #E2E2E2

c1 = #C87A8A
c2 = #6F9C60
c3 = #AC8C4E
c4 = #6695BE
c5 = #B37EBE
c6 = #4D9E95

c9  = #FB9EB1
c10 = #88C96F
c11 = #DEB356
c12 = #77C0F9
c13 = #EC9BFC
c14 = #60CABE
