# ansil16 palette: mypal-dark
# Designed in designer/index.html.

bg = #000000
fg = #FFFFFF

# grayscale ramp
c0  = #343434
c7  = #8B8B8B
c8  = #555555
c15 = #C9C9C9

# standard row
c1  = #FF6C93
c2  = #98A601
c3  = #DE8A2C
c4  = #46A1FF
c5  = #BD82FF
c6  = #00B1A5

# bright row
c9  = #FC9EAF
c10 = #8CCA54
c11 = #F2AB3F
c12 = #75BFFF
c13 = #CBA9FF
c14 = #00D0AD
